name: PR metadata annotation

on:
  workflow_dispatch
  #pull_request:
    #types: [opened, reopened, synchronize]       
jobs:

  annotate-pr:
    runs-on: self-hosted
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: anuraagkb/PR-metadata-action@main
        with:
          workspace: D:\HCL\hclonetest\workspace
          project: PT1
          suite: Test1
          input4: D:\HCL\hclonetest\workspace
          input5: PT1
          input6: Test1
          input7: D:\HCL\hclonetest\workspace
          input8: PT1
          input9: Test1
          input10: D:\HCL\hclonetest\workspace
          input11: PT1
          input12: Test1          
